#version: '3'
#services:
app:
  build: .
  dockerfile: Dockerfile
  ports:
    - 3000:80
  volumes:
    - ../:/var/www/html/
  links:
    - db:db
db:
  image: mysql:5.7.36
  #command: --default-authentication-plugin=mysql_native_password
  ports:
    - 3306:3306
  volumes:
    - ~/docker/mysql-data-new-equipo:/var/lib/mysql
  environment:
    MYSQL_USER: 'new_equipo'
    MYSQL_PASSWORD: '123456'
    MYSQL_DATABASE: 'new_equipo'
    MYSQL_ROOT_PASSWORD: '123456'

